### ISSUE TITLE
Exclude file from rendering

### ISSUE THREAD

**Issue by tameroski** [mrkmg/laravel-elixir-pug#10]
Including pug files is now working find, but includes are also compiling to blade files in the views folder. Is there a way to exclude a folder or files from being compiled ?

**Comment by mrkmg** [comment]
Not currently, I will investigate adding this functionality.

**Comment by mrkmg** [comment]
Version 1.3.0 now allows an 'exclude' option to be set. Should exclude any "Glob" passed to it from being created as it's own file, but will still trigger parents to be regenerated if they are changed.
