### ISSUE TITLE
gulp watch merging options across multiple calls

### ISSUE THREAD

**Issue by borger** [mrkmg/laravel-elixir-pug#11]
When I run a gulp watch with two or more calls to pug, it gets confused, and runs all the "src"s into the second (or last) options, so it will mix all the src files and process them as if there was only the second call ( on the sample below, with blade: true, and dest to 'resources/views/'), what I expected was to have their srcs saves into each of their dests value following each of the calls options, as they do if I just run gulp.

> mix.pug({
>     blade: false,
>     src: 'resources/pug/vue/',
>     dest: 'resources/vue/',
>     })
> .pug({
>     blade: true,
>     src: 'resources/pug/views/',
>     dest: 'resources/views/'
>     });

**Important Note: This won't happen if I just run gulp, it only happens with watch.**

**Comment by mrkmg** [comment]
Oh goodness. I will look into this asap.

**Comment by mrkmg** [comment]
With a very simple test I am getting even weird results...

The src files from the first call are being put into the second calls dest, and the second calls src files are not being compiled at all. So weird...

**Comment by mrkmg** [comment]
And even more weirdness. Changed the paths and now the second call is being ignored all together. Totally baffled at this point...

**Comment by borger** [comment]
Indeed! I did play around with it, and as you said got some weird results, that's why I decided to log this one so you could review... I am also looking into it, if I find anything I'll pull request...

**Comment by mrkmg** [comment]
I think I found a potential solution. Running more tests on it before I push it out.

**Comment by mrkmg** [comment]
@borger I have made the fixes, ran a battery of tests on my repos. I think we are good to go. I have a PR to a broken dependency, so if that is accepted, there will be another minor bump again reverting back to their package

**Comment by borger** [comment]
That's great man!.. Thanks for the quick support!
