### ISSUE TITLE
Adding mixin files before compiling 

### ISSUE THREAD

**Issue by endder** [mrkmg/laravel-elixir-pug#3]
Hi all, I have a mixin file (https://gist.github.com/JaminFarr/0b875916b39bf83c4b06) which i need to add before the laravel-elixir-pug complies.

currently I am having to add it to every template which needs access to the mixin.
**example** 

```
include ./../../../_mixin.jade
article.article-card-large
    .row
..........

```

Would there be a way i can get the laravel-elixir-pug to load it first before compiling the .jade templates or is there another way.

Thanks
Tom

**Comment by mrkmg** [comment]
I do not believe this is something that pug nor gulp-pug supports, so it wouldn't make sense to implement it here. Obviously, if pug adds support for "global includes", then I would add that support here.

I honestly do not believe that pug will add this feature.
