### ISSUE TITLE
Parent file not updating

### ISSUE THREAD

**Issue by eirabben** [mrkmg/laravel-elixir-pug#9]
When a `.pug` file is included in another file, the parent is not updated when the included file is edited. I have to manually make a change to the parent to make Gulp/Webpack process it.

Is there any way to track includes in pug, and update all files that reference a certain file?

**Comment by carduz** [comment]
@mrkmg I think that gulp-changed causes that

**Comment by mrkmg** [comment]
It did, I need to incorporate https://github.com/pure180/gulp-pug-inheritance

I should have this done today.

**Comment by mrkmg** [comment]
@eirabben Can you please check out version 1.2.0. If your issue is still persisting, please let me know!

**Comment by eirabben** [comment]
@mrkmg Works perfectly now. Great job!
